using System.Collections.Generic;

public static class Texts {
	public static Dictionary<string, string> texts = new Dictionary<string, string>	{
		{ "Start", "Burglars broke into my home, they're beating me up and demanding I open the safe for them. I don't remember the combination, or what's the safe for..." },
		{ "safe", "Safe... Safe... Safe? Do I keep my valuables there? Am I supposed to remember the combination? It must mean something to me." },
		{ "hunting-trophy", "This was my first hunting trophy. I only kept the head. Did I go to Africa to hunt?" },
		{ "binoculars", "These would be quite useful for a hunter." },
		{ "boots", "My feet still remember the thousands of footprints I left in the sand." },
		{ "book-hunting", "Ah, I've read this book a few times through. I haven't seen Africa for a long time, but savanna still calls me." },
		{ "rifle", "Aaaahhh, I remember now. The best gift I've ever received, a custom made replica of a german rifle, specially fashioned for hunting, which quickly became my favourite hobby." },
		{ "burglars", "I am far more dangerous than these guys are or ever will be." },
		{ "photo-zebra", "Africa? I've been to Africa? I can't recall, but I've definitely taken this picture." },
		{ "photo2-pro", "This is not the work of an amateur, however I don't think it's me. Who is this?" },
		{ "camera", "This is not a cheap camera, I remember paying quite a fortune for it. Am I a photographer of some sort? I must have some undeveloped film lying around..." },
		{ "book-nat.geo", "I remember seeing all of these in the wild. Did I take these pictures?" },
		{ "poster-map_with_tags", "I remember traveling the world quite a bit. Planes, trains, long talks with strangers..." },
		{ "film-roll", "No, I never developed my films and I don't even know how. I don't think I'm a photographer." },
		{ "camping-bag", "I remember packing this many times. I wonder where have I been?" },
		{ "@passport", "These are all my passports, under different names and with different pictures. Why would I have so many?" },
		{ "big_box-tv", "A TV? Since when do I own a TV? When did I get it?" },
		{ "table", "I see myself spending countless hours at this table, probably working on something. Surely, the combination could be related to my work." },
		{ "@typewriter", "I certainly remember using this for work. Could I be a writer or a journalist of some kind? Have I left some unfinished work?" },
		{ "book-memoirs", "Memoirs? Are these mine? Did I write them with this typewriter?" },
		{ "manuscript", "No, I'm not a writer, but my life was eventful enough for a whole series of books." },
		{ "scratchpad", "Did I take notes with this? Wouldn't it be easier to use a recorder of some sort?" },
		{ "@tape-recorder", "Ah, yes, I used something simillar, but much smaller. Definitely not the kind a journalist would use." },
		{ "@newspaper", "There was an article in this paper... Something about a government agent, I think I knew him before." },
		{ "prize-trophy", "Being struck with my own trophy! First place... What was it? Could the date be important?" },
		{ "baseball-bat", "Am I player? Did I compete? I remember tuning in on the radio to follow the game..." },
		{ "@crossbow", "Ah, of course, I got first place in target shooting. I had to use all kinds of weapons in my prime." },
		{ "baseball", "This can't be right, I've not played baseball a single day in my life. Why do I have this bat then?" },
		{ "poster-painting", "Did I paint this?" },
		{ "table-painterly", "I remember.. I must still have my supplies around here." },
		{ "dyes", "I'm not sure I remember ever buying these. My brushes should be here somewhere..." },
		{ "other-pictures", "Did I draw these? A zebra.. I think I had a photo of one here somewhere. I must be a big animal lover." },
		{ "painting-canvas", "No, this can't be right. I've never had a canvas. I am no artist, I would've remembered." },
		{ "book-art", "I remember this book! Did I write it? Am I an artist? I must have my canvas nearby..." },
		{ "big_box-terrarium", "Did I remember to feed my turtle? Not that it matters now.." },
		{ "brushes", "I don't remember using these brushes, but maybe my hands do." },
		{ "@pictures-faces", "Who are these people? They do not look alike, yet I feel it's the same person." },
		{ "@clock", "My time has long gone, I am not the man I used to be, but I would never get in such situation back in the day." },
		{ "big_box-radio", "Ah, there's always this catchy tune, I'd never forget it." },
		{ "other-books", "I've read a lot of books in my time. None of them really stuck with me, though." },
		{ "remember-password", "NORMAL ENDING" },
		{ "passport-reveal", "I was known under so many names and so many faces that I've lost count." },
		{ "taperecorder-reveal", "As my memory started failing, I used this to remind me of things. But I remember now, oh I do..." },
		{ "crossbow-reveal", "I once killed three men in a bar armed only with a cup. These two? Now, what have we got here.." },
		{ "typewriter-reveal", "This was the most advanced cryptographic equipment decades ago. Easily passes as a regular typewriter." },
		{ "pictures-reveal", "I used to do a rough sketch on paper before applying makeup." },
		{ "clock-reveal", "The time waits for no one. I had to quit, I was too old for this shit." },
		{ "newspaper-reveal", "My old partner. We could only talk during assignments, never outside work. I wonder what he's up to." },
		{ "lampshade", "More than once I killed a man with a lampshade, it has a good heavy feel to it. However, it's a bit out of reach." },
		{ "belts", "Good thing I still carry a knife with me. My hands remember all the moves..." },
		{ "burglars-rip", "Double-click this passage to edit it." }
	};
}